export const DEFAULT_NODES = [
  // 1. Cover Section
  {
    id: 'container-cover',
    type: 'container',
    sectionType: 'cover',
    label: 'Section Cover (Sampul Utama)',
    style: {
      flexDirection: 'column',
      justify: 'center',
      alignItems: 'center',
      gap: 16,
      padding: '60px 24px',
      backgroundColor: '#eff2ef',
      backgroundImage: '',
      backgroundOverlayColor: 'rgba(0,0,0,0.25)',
      backgroundOverlayOpacity: 0.5,
      width: '100%',
      height: 'auto',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-cover-title',
        type: 'heading',
        content: '{cover_title}',
        isDynamic: true,
        binding: 'cover_title',
        style: {
          color: '#ffffff',
          fontSize: 14,
          textAlign: 'center',
          fontFamily: 'Montserrat',
          fontWeight: 'bold',
          margin: '0px 0px 4px 0px',
          letterSpacing: '2px',
          textTransform: 'uppercase',
        },
      },
      {
        id: 'heading-cover-names',
        type: 'heading',
        content: '{nama_mempelai}',
        isDynamic: true,
        binding: 'nama_mempelai',
        style: {
          color: '#ffffff',
          fontSize: 32,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
          margin: '0px 0px 8px 0px',
          lineHeight: '1.2',
        },
      },
      {
        id: 'text-cover-desc',
        type: 'text',
        content: 'Kami mengundang Anda untuk merayakan momen bahagia pernikahan kami.',
        style: {
          color: '#f3f4f6',
          fontSize: 12,
          textAlign: 'center',
          fontFamily: 'Inter',
          margin: '0px 0px 16px 0px',
        },
      },
      {
        id: 'button-cover-open',
        type: 'button',
        content: 'Buka Undangan',
        style: {
          backgroundColor: '#e36397',
          color: '#ffffff',
          fontSize: 12,
          padding: '10px 24px',
          borderRadius: 8,
          width: 'auto',
        },
      },
    ],
  },

  // 2. Hero Banner Section
  {
    id: 'container-hero',
    type: 'container',
    sectionType: 'hero',
    label: 'Section Hero Banner',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 16,
      padding: '48px 24px',
      backgroundColor: '#ffffff',
      width: '100%',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-hero-title',
        type: 'heading',
        content: 'The Wedding Of {nama_mempelai}',
        style: {
          color: '#1e293b',
          fontSize: 26,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'text-hero-date',
        type: 'text',
        content: '{tanggal_acara} • {lokasi_acara}',
        style: {
          color: '#64748b',
          fontSize: 13,
          textAlign: 'center',
          fontFamily: 'Inter',
        },
      },
      {
        id: 'countdown-hero',
        type: 'countdown',
        content: '2026-09-21T09:00:00',
        style: {
          color: '#e36397',
          fontSize: 16,
          textAlign: 'center',
        },
      },
    ],
  },

  // 3. Opening Section
  {
    id: 'container-opening',
    type: 'container',
    sectionType: 'opening',
    label: 'Section Ucapan Pembuka',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 12,
      padding: '36px 24px',
      backgroundColor: '#f8fafc',
      width: '100%',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-opening-title',
        type: 'heading',
        content: '{salam_pembuka}',
        isDynamic: true,
        binding: 'salam_pembuka',
        style: {
          color: '#1e293b',
          fontSize: 18,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'text-opening-verse',
        type: 'text',
        content: '{kutipan_ayat}',
        isDynamic: true,
        binding: 'kutipan_ayat',
        style: {
          color: '#64748b',
          fontSize: 13,
          textAlign: 'center',
          fontFamily: 'Inter',
          lineHeight: '1.6',
        },
      },
      {
        id: 'text-opening-surah',
        type: 'text',
        content: '{nama_surah}',
        isDynamic: true,
        binding: 'nama_surah',
        style: {
          color: '#e36397',
          fontSize: 12,
          textAlign: 'center',
          fontFamily: 'Inter',
          fontWeight: 'bold',
        },
      },
    ],
  },

  // 4. Bride & Groom Section
  {
    id: 'container-bride_groom',
    type: 'container',
    sectionType: 'bride_groom',
    label: 'Section Profil Mempelai',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 20,
      padding: '40px 24px',
      backgroundColor: '#ffffff',
      width: '100%',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-bg-title',
        type: 'heading',
        content: 'Pasangan Mempelai',
        style: {
          color: '#e36397',
          fontSize: 24,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'image-groom-photo',
        type: 'image',
        binding: 'fotoPria',
        content: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        style: {
          width: '130px',
          height: '130px',
          borderRadius: 65,
          objectFit: 'cover',
        },
      },
      {
        id: 'heading-groom-name',
        type: 'heading',
        content: '{groom_name}',
        style: {
          color: '#1e293b',
          fontSize: 20,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'text-groom-parents',
        type: 'text',
        content: 'Putra dari {ortu_pria}',
        isDynamic: true,
        binding: 'ortu_pria',
        style: {
          color: '#64748b',
          fontSize: 12,
          textAlign: 'center',
          fontFamily: 'Inter',
        },
      },
      {
        id: 'image-bride-photo',
        type: 'image',
        binding: 'fotoWanita',
        content: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
        style: {
          width: '130px',
          height: '130px',
          borderRadius: 65,
          objectFit: 'cover',
        },
      },
      {
        id: 'heading-bride-name',
        type: 'heading',
        content: '{bride_name}',
        style: {
          color: '#1e293b',
          fontSize: 20,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'text-bride-parents',
        type: 'text',
        content: 'Putri dari {ortu_wanita}',
        isDynamic: true,
        binding: 'ortu_wanita',
        style: {
          color: '#64748b',
          fontSize: 12,
          textAlign: 'center',
          fontFamily: 'Inter',
        },
      },
    ],
  },

  // 5. Event Schedule Section
  {
    id: 'container-event_schedule',
    type: 'container',
    sectionType: 'event_schedule',
    label: 'Section Waktu & Lokasi Acara',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 16,
      padding: '40px 24px',
      backgroundColor: '#f8fafc',
      width: '100%',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-schedule-title',
        type: 'heading',
        content: 'Waktu & Lokasi Acara',
        style: {
          color: '#1e293b',
          fontSize: 22,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'feed-event-list',
        type: 'container',
        isEventFeed: true,
        label: 'Daftar Jadwal Acara',
        style: {
          flexDirection: 'column',
          gap: 16,
          width: '100%',
          backgroundColor: 'transparent',
          padding: '0px',
        },
        children: [
          {
            id: 'card-event-master',
            type: 'container',
            label: 'Kartu Master Acara',
            style: {
              flexDirection: 'column',
              alignItems: 'center',
              gap: 10,
              padding: '24px 20px',
              backgroundColor: '#ffffff',
              borderRadius: 16,
              borderStyle: 'solid',
              borderWidth: 1,
              borderColor: '#e2e8f0',
              boxShadow: '0 4px 16px rgba(0,0,0,0.04)',
              width: '100%',
            },
            children: [
              {
                id: 'event-master-title',
                type: 'heading',
                content: '{{event_title}}',
                style: {
                  fontSize: 20,
                  color: '#1e293b',
                  fontWeight: 'bold',
                  fontFamily: 'Playfair Display',
                  textAlign: 'center',
                  margin: '0px 0px 4px 0px',
                },
              },
              {
                id: 'event-master-datetime',
                type: 'text',
                content: '📅 {{event_date}} • 🕘 {{event_time}}',
                style: {
                  fontSize: 13,
                  color: '#e36397',
                  fontWeight: 'bold',
                  fontFamily: 'Inter',
                  textAlign: 'center',
                  margin: '0px 0px 4px 0px',
                },
              },
              {
                id: 'event-master-location',
                type: 'text',
                content: '📍 {{event_location}}',
                style: {
                  fontSize: 14,
                  color: '#334155',
                  fontWeight: 'bold',
                  fontFamily: 'Inter',
                  textAlign: 'center',
                  margin: '0px 0px 2px 0px',
                },
              },
              {
                id: 'event-master-address',
                type: 'text',
                content: '{{event_address}}',
                style: {
                  fontSize: 12,
                  color: '#64748b',
                  fontFamily: 'Inter',
                  textAlign: 'center',
                  margin: '0px 0px 8px 0px',
                },
              },
              {
                id: 'event-master-btn-map',
                type: 'button',
                content: '🗺️ Buka Google Maps',
                buttonAction: 'google-maps',
                style: {
                  backgroundColor: '#e36397',
                  color: '#ffffff',
                  borderRadius: 20,
                  padding: '8px 20px',
                  fontSize: 12,
                  fontWeight: 'bold',
                },
              },
            ],
          },
        ],
      },
      {
        id: 'map-schedule',
        type: 'map',
        content: 'Hotel Mulia Jakarta',
        style: {
          borderRadius: 12,
          width: '100%',
          height: '200px',
        },
      },
    ],
  },

  // 6. Live Streaming Section
  {
    id: 'container-live_streaming',
    type: 'container',
    sectionType: 'live_streaming',
    label: 'Section Virtual Live Streaming',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 12,
      padding: '32px 24px',
      backgroundColor: '#ffffff',
      width: '100%',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-livestream-title',
        type: 'heading',
        content: 'Siaran Langsung Acara (Virtual Event)',
        style: {
          color: '#e36397',
          fontSize: 20,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'text-livestream-desc',
        type: 'text',
        content: 'Bagi keluarga dan kerabat yang berhalangan hadir secara langsung, Anda dapat mengikuti prosesi acara secara virtual melalui siaran langsung di bawah ini.',
        style: {
          color: '#64748b',
          fontSize: 12,
          textAlign: 'center',
          fontFamily: 'Inter',
        },
      },
      {
        id: 'button-livestream-link',
        type: 'button',
        content: '🎥 Tonton Live Streaming',
        style: {
          backgroundColor: '#e36397',
          color: '#ffffff',
          fontSize: 13,
          padding: '12px 28px',
          borderRadius: 10,
          width: 'auto',
          fontWeight: 'bold',
        },
      },
    ],
  },

  // 7. Love Story Section
  {
    id: 'container-love_story',
    type: 'container',
    sectionType: 'love_story',
    label: 'Section Kisah Cinta',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 16,
      padding: '36px 24px',
      backgroundColor: '#f8fafc',
      width: '100%',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-lovestory-title',
        type: 'heading',
        content: 'Perjalanan Cinta Kami',
        style: {
          color: '#1e293b',
          fontSize: 22,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'text-lovestory-desc',
        type: 'text',
        content: 'Kisah kenangan indah perjalanan kami dari awal bertemu hingga mengikat janji suci pernikahan.',
        style: {
          color: '#64748b',
          fontSize: 12,
          textAlign: 'center',
          fontFamily: 'Inter',
          margin: '0px 0px 16px 0px',
        },
      },
      {
        id: 'feed-lovestory-list',
        type: 'container',
        isStoryFeed: true,
        label: 'Daftar Kisah Cinta',
        style: {
          display: 'flex',
          flexDirection: 'column',
          gap: 16,
          width: '100%',
        },
        children: [
          {
            id: 'card-story-master',
            type: 'container',
            label: 'Kartu Master Cerita',
            style: {
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: 10,
              padding: '20px 18px',
              backgroundColor: '#ffffff',
              borderRadius: 16,
              borderStyle: 'solid',
              borderWidth: 1,
              borderColor: '#e2e8f0',
              boxShadow: '0 4px 16px rgba(0,0,0,0.04)',
              width: '100%',
            },
            children: [
              {
                id: 'story-master-badge',
                type: 'text',
                content: '📅 {story_year}',
                style: {
                  fontSize: 12,
                  color: '#e36397',
                  fontWeight: 'bold',
                  fontFamily: 'Inter',
                  backgroundColor: '#fdf2f8',
                  padding: '4px 14px',
                  borderRadius: 20,
                  borderStyle: 'solid',
                  borderWidth: 1,
                  borderColor: '#fbcfe8',
                  textAlign: 'center',
                },
              },
              {
                id: 'story-master-title',
                type: 'heading',
                content: '{story_title}',
                style: {
                  fontSize: 18,
                  color: '#1e293b',
                  fontWeight: 'bold',
                  fontFamily: 'Playfair Display',
                  textAlign: 'center',
                },
              },
              {
                id: 'story-master-desc',
                type: 'text',
                content: '{story_description}',
                style: {
                  fontSize: 13,
                  color: '#64748b',
                  fontFamily: 'Inter',
                  textAlign: 'center',
                  lineHeight: '1.6',
                },
              },
              {
                id: 'story-master-img',
                type: 'image',
                content: '{story_image}',
                style: {
                  width: '100%',
                  height: '200px',
                  borderRadius: 12,
                  objectFit: 'cover',
                  margin: '8px 0px 0px 0px',
                },
              },
            ],
          },
        ],
      },
    ],
  },

  // 8. Gallery Section
  {
    id: 'container-gallery',
    type: 'container',
    sectionType: 'gallery',
    label: 'Section Galeri Foto',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 16,
      padding: '40px 24px',
      backgroundColor: '#ffffff',
      width: '100%',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-gallery-title',
        type: 'heading',
        content: 'Galeri Momen Bahagia',
        style: {
          color: '#e36397',
          fontSize: 22,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'text-gallery-desc',
        type: 'text',
        content: 'Momen-momen indah kebersamaan kami yang terekam dalam kenangan abadi.',
        style: {
          color: '#64748b',
          fontSize: 12,
          textAlign: 'center',
          fontFamily: 'Inter',
          margin: '0px 0px 16px 0px',
        },
      },
      {
        id: 'feed-gallery-grid',
        type: 'container',
        isGalleryFeed: true,
        label: 'Grid Galeri Foto',
        style: {
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(130px, 1fr))',
          gap: 12,
          width: '100%',
        },
        children: [
          {
            id: 'image-gallery-master',
            type: 'image',
            label: 'Master Item Foto Galeri',
            showInGallery: true,
            content: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&auto=format&fit=crop&q=80',
            style: {
              width: '100%',
              aspectRatio: '1 / 1',
              borderRadius: 14,
              objectFit: 'cover',
              boxShadow: '0 4px 15px rgba(0,0,0,0.04)',
            },
          },
        ],
      },
    ],
  },

  // 9. RSVP Section
  {
    id: 'container-rsvp',
    type: 'container',
    sectionType: 'rsvp',
    label: 'Section RSVP Kehadiran',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 16,
      padding: '40px 24px',
      backgroundColor: '#f8fafc',
      width: '100%',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-rsvp-title',
        type: 'heading',
        content: 'Konfirmasi Kehadiran (RSVP)',
        style: {
          color: '#1e293b',
          fontSize: 22,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'text-rsvp-desc',
        type: 'text',
        content: 'Mohon konfirmasi kehadiran Anda untuk membantu kami menyiapkan konsumsi & tempat acara.',
        style: {
          color: '#64748b',
          fontSize: 12,
          textAlign: 'center',
          fontFamily: 'Inter',
        },
      },
    ],
  },

  // 10. Wishes Section
  {
    id: 'container-wishes',
    type: 'container',
    sectionType: 'wishes',
    label: 'Section Ucapan & Doa Restu',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 16,
      padding: '40px 24px',
      backgroundColor: '#ffffff',
      width: '100%',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-wishes-title',
        type: 'heading',
        content: 'Ucapan & Doa Restu Tamu',
        style: {
          color: '#e36397',
          fontSize: 22,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'text-wishes-desc',
        type: 'text',
        content: 'Tinggalkan pesan ucapan dan doa terbaik Anda untuk kedua mempelai.',
        style: {
          color: '#64748b',
          fontSize: 12,
          textAlign: 'center',
          fontFamily: 'Inter',
        },
      },
      {
        id: 'feed-wishes-list',
        type: 'container',
        isWishesFeed: true,
        style: {
          flexDirection: 'column',
          gap: 12,
          width: '100%',
          backgroundColor: 'transparent',
          padding: '0px',
        },
      },
    ],
  },

  // 11. Gift Section
  {
    id: 'container-gift',
    type: 'container',
    sectionType: 'gift',
    label: 'Section Amplop Digital & Kado',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 16,
      padding: '40px 24px',
      backgroundColor: '#f8fafc',
      width: '100%',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-gift-title',
        type: 'heading',
        content: 'Amplop Digital & Kado Fisik',
        style: {
          color: '#1e293b',
          fontSize: 22,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'text-gift-desc',
        type: 'text',
        content: 'Doa restu Anda merupakan karunia terindah bagi kami. Bagi yang ingin memberikan tanda kasih, dapat mengirimkan angpao digital di bawah ini.',
        style: {
          color: '#64748b',
          fontSize: 12,
          textAlign: 'center',
          fontFamily: 'Inter',
        },
      },
      {
        id: 'widget-gift-registry',
        type: 'container',
        widgetType: 'gift-widget',
        label: 'Widget Amplop Digital',
        style: {
          width: '100%',
          padding: '0px',
          backgroundColor: 'transparent',
        },
      },
    ],
  },

  // 12. IG Stories Section
  {
    id: 'container-ig_stories',
    type: 'container',
    sectionType: 'ig_stories',
    label: 'Section Instagram Stories',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 12,
      padding: '32px 24px',
      backgroundColor: '#ffffff',
      width: '100%',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-ig-title',
        type: 'heading',
        content: 'Bagikan Momen di Instagram Stories',
        style: {
          color: '#e36397',
          fontSize: 20,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'text-ig-desc',
        type: 'text',
        content: 'Bagikan kebahagiaan ini ke Story Instagram Anda dengan tagar {hashtag}.',
        isDynamic: true,
        binding: 'hashtag',
        style: {
          color: '#64748b',
          fontSize: 12,
          textAlign: 'center',
          fontFamily: 'Inter',
        },
      },
    ],
  },

  // 13. Thank You Section
  {
    id: 'container-thank_you',
    type: 'container',
    sectionType: 'thank_you',
    label: 'Section Ucapan Terimakasih',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 12,
      padding: '40px 24px',
      backgroundColor: '#f8fafc',
      width: '100%',
      borderRadius: 16,
      margin: '0px 0px 24px 0px',
    },
    children: [
      {
        id: 'heading-thankyou-title',
        type: 'heading',
        content: 'Terima Kasih',
        style: {
          color: '#1e293b',
          fontSize: 24,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
      {
        id: 'text-thankyou-desc',
        type: 'text',
        content: '{pesan_penutup}',
        isDynamic: true,
        binding: 'pesan_penutup',
        style: {
          color: '#64748b',
          fontSize: 13,
          textAlign: 'center',
          fontFamily: 'Inter',
        },
      },
      {
        id: 'heading-thankyou-family',
        type: 'heading',
        content: 'Kami yang berbahagia,\n{nama_keluarga_penutup}',
        isDynamic: true,
        binding: 'nama_keluarga_penutup',
        style: {
          color: '#e36397',
          fontSize: 16,
          textAlign: 'center',
          fontFamily: 'Playfair Display',
          fontWeight: 'bold',
        },
      },
    ],
  },

  // 14. Footer Section
  {
    id: 'container-footer',
    type: 'container',
    sectionType: 'footer',
    label: 'Section Footer & Watermark',
    style: {
      flexDirection: 'column',
      alignItems: 'center',
      gap: 8,
      padding: '24px',
      backgroundColor: '#0f172a',
      color: '#94a3b8',
      width: '100%',
      borderRadius: 16,
      margin: '0px',
    },
    children: [
      {
        id: 'text-footer-watermark',
        type: 'text',
        content: 'Digital Invitation Created with JoinMe.id',
        style: {
          color: '#94a3b8',
          fontSize: 11,
          textAlign: 'center',
          fontFamily: 'Inter',
        },
      },
    ],
  },
];
